baseURL = "http://example.org/"
languageCode = "en-us"
title = "LibreBadge"
theme = "librebadge"
[params]
  githubURL = "http://github.com/LibreBadge/LibreBadge"
  logo = "librebadgelogo.svg"
  description = "LibreBadge is an open-source web based ID Badge solution written in Python Django"